#!/bin/bash
#$ -cwd
#$ -o /dev/null
#$ -e /dev/null
# Set the number of processes here:
#$ -pe smp 32
# Set the number of processors (if different from the above) here:
setenv OMP_NUM_THREADS $NSLOTS
# Change the name of the execuatable here:
./filter image1.bmp image_results/cns_32threads.bmp 32> image_results/output_32threads.txt
