#!/bin/bash
#$ -cwd
#$ -o /dev/null
#$ -e /dev/null
# Set the number of processes here:
#$ -pe mpi 4
# Set the number of processors (if different from the above) here:
setenv OMP_NUM_THREADS 16
# Change the name of the execuatable here:
gcc cmd_run.c -o ff
ff
./filter21 maneet.jpeg cns.jpeg 4> results/output_4_16.txt
